### ISSUE TITLE
验证码是GIF动画了

### ISSUE THREAD

**Issue by bingcheng1998** [Hanyang-Li/BotFarmer-1point3acres#2]
新的验证码变成会动的了
以下是其中一帧
![image](https://user-images.githubusercontent.com/26592478/87492847-10e76300-c67e-11ea-9d6c-19aa003a8d29.png)
导致识别失败

error:
```sh
Traceback (most recent call last):
  File "automatic.py", line 435, in <module>
    check_in()
  File "automatic.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "automatic.py", line 134, in check_in
    verify_code = _get_verify_code('S00')
  File "automatic.py", line 317, in _get_verify_code
    verify_code = _recognize_verify(verify_image)
  File "automatic.py", line 365, in _recognize_verify
    rgb = pix[x, y][:3]
TypeError: 'int' object is not subscriptable
```

**Comment by Hanyang-Li** [comment]
我前几天提交了一份针对更新的代码，你再clone下试试，应该是可以处理动图了:)
